package org.example.webstore.item.enums;

public enum Subcategories {
    // ELECTRONICS
    AUDIO_DEVICES,
    PHONES_AND_ACCESSORIES,
    COMPUTERS_AND_LAPTOPS,
    MONITORS_AND_TELEVISIONS,

    // CHILDREN_GOODS
    TOYS,
    CHILDREN_CLOTHES,

    // CARS
    PASSENGER_CARS,
    CARGO_VEHICLES,
    MOTORCYCLES,

    // CLOTHES_AND_SHOES
    SHOES,
    MEN_CLOTHING,
    WOMEN_CLOTHING,

    // SPORTS_AND_OUTDOOR_ACTIVITIES
    BICYCLES,
    SPORTS_EQUIPMENT,
    CAMPING_AND_HIKING
}

